<script>
  import {
    Link,
    Copy,
    Edit,
    Trash2,
    Eye,
    EyeOff,
    Check,
    X,
    ChevronDown,
    ChevronUp,
    ChevronLeft,
    ChevronRight,
    Plus,
    Minus,
    Search,
    Filter,
    Settings,
    User,
    Users,
    LogOut,
    Menu,
    X as XIcon,
    Home,
    BarChart3,
    FileText,
    Folder,
    Tag,
    Calendar,
    Clock,
    Lock,
    Unlock,
    Shield,
    Key,
    QrCode,
    Share2,
    ExternalLink,
    Download,
    Upload,
    RefreshCw,
    RotateCw,
    Zap,
    TrendingUp,
    TrendingDown,
    Activity,
    Globe,
    Monitor,
    Smartphone,
    Tablet,
    MousePointer2,
    MapPin,
    AlertCircle,
    AlertTriangle,
    Info,
    CheckCircle,
    XCircle,
    HelpCircle,
    Mail,
    Phone,
    MessageCircle,
    Send,
    Save,
    LogIn,
    UserPlus,
    MoreVertical,
    MoreHorizontal,
    Sliders,
    ArrowRight,
    ArrowLeft,
    ArrowUp,
    ArrowDown,
    Play,
    Pause,
    RotateCcw,
    Sun,
    Moon,
    Star,
    Heart,
    Bookmark,
    Bell,
    BellOff,
    Search as SearchIcon,
    Loader2,
    Sparkles,
    Target,
    Layers,
    GitBranch,
    Workflow,
    Database,
    Server,
    HardDrive,
    Cpu,
    Wifi,
    Bluetooth,
    Usb,
    Image,
    Video,
    Music,
    File,
    Files,
    FolderOpen,
    FolderClosed,
    Archive,
    Package,
    Box,
    ShoppingBag,
    ShoppingCart,
    CreditCard,
    DollarSign,
    Percent,
    Award,
    Trophy,
    Medal,
    Crown,
    Gem,
    Flame,
    Lightbulb,
    Rocket,
    Hammer,
    Wrench,
    Cog,
    Settings as SettingsIcon,
    Code,
    Camera,
    Gift
  } from 'lucide-svelte';

  export let name;
  export let size = 20;
  export let strokeWidth = 2;
  export let className = '';
  export let stroke;
  export let color;

  const iconMap = {
    'link': Link,
    'copy': Copy,
    'edit': Edit,
    'trash': Trash2,
    'trash-2': Trash2,
    'eye': Eye,
    'eye-off': EyeOff,
    'check': Check,
    'x': X,
    'close': XIcon,
    'chevron-down': ChevronDown,
    'chevron-up': ChevronUp,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    'plus': Plus,
    'minus': Minus,
    'search': Search,
    'filter': Filter,
    'settings': Settings,
    'cog': Cog,
    'user': User,
    'users': Users,
    'log-out': LogOut,
    'menu': Menu,
    'home': Home,
    'chart': BarChart3,
    'bar-chart-3': BarChart3,
    'file': FileText,
    'file-text': FileText,
    'folder': Folder,
    'tag': Tag,
    'calendar': Calendar,
    'clock': Clock,
    'lock': Lock,
    'unlock': Unlock,
    'shield': Shield,
    'key': Key,
    'qr-code': QrCode,
    'share': Share2,
    'share-2': Share2,
    'external-link': ExternalLink,
    'download': Download,
    'upload': Upload,
    'refresh': RefreshCw,
    'refresh-cw': RefreshCw,
    'rotate': RotateCw,
    'rotate-cw': RotateCw,
    'zap': Zap,
    'trending-up': TrendingUp,
    'trending-down': TrendingDown,
    'activity': Activity,
    'globe': Globe,
    'monitor': Monitor,
    'smartphone': Smartphone,
    'tablet': Tablet,
    'mouse': MousePointer2,
    'mouse-pointer-2': MousePointer2,
    'map-pin': MapPin,
    'alert-circle': AlertCircle,
    'alert-triangle': AlertTriangle,
    'info': Info,
    'check-circle': CheckCircle,
    'x-circle': XCircle,
    'help-circle': HelpCircle,
    'mail': Mail,
    'phone': Phone,
    'message': MessageCircle,
    'message-circle': MessageCircle,
    'send': Send,
    'save': Save,
    'log-in': LogIn,
    'user-plus': UserPlus,
    'more-vertical': MoreVertical,
    'more-horizontal': MoreHorizontal,
    'sliders': Sliders,
    'arrow-right': ArrowRight,
    'arrow-left': ArrowLeft,
    'arrow-up': ArrowUp,
    'arrow-down': ArrowDown,
    'play': Play,
    'pause': Pause,
    'rotate-ccw': RotateCcw,
    'sun': Sun,
    'moon': Moon,
    'star': Star,
    'heart': Heart,
    'bookmark': Bookmark,
    'bell': Bell,
    'bell-off': BellOff,
    'loader': Loader2,
    'loader-2': Loader2,
    'sparkles': Sparkles,
    'target': Target,
    'layers': Layers,
    'git-branch': GitBranch,
    'workflow': Workflow,
    'database': Database,
    'server': Server,
    'hard-drive': HardDrive,
    'cpu': Cpu,
    'wifi': Wifi,
    'bluetooth': Bluetooth,
    'usb': Usb,
    'image': Image,
    'video': Video,
    'music': Music,
    'files': Files,
    'folder-open': FolderOpen,
    'folder-closed': FolderClosed,
    'archive': Archive,
    'package': Package,
    'box': Box,
    'shopping-bag': ShoppingBag,
    'shopping-cart': ShoppingCart,
    'credit-card': CreditCard,
    'dollar-sign': DollarSign,
    'percent': Percent,
    'award': Award,
    'trophy': Trophy,
    'medal': Medal,
    'crown': Crown,
    'gem': Gem,
    'flame': Flame,
    'lightbulb': Lightbulb,
    'rocket': Rocket,
    'hammer': Hammer,
    'wrench': Wrench,
    'code': Code,
    'camera': Camera,
    'gift': Gift
  };

  function getIcon() {
    if (!name) return null;
    return iconMap[name.toLowerCase()] || null;
  }

  $: IconComponent = getIcon();
</script>

{#if IconComponent}
  <svelte:component
    this={IconComponent}
    {size}
    {strokeWidth}
    {stroke}
    {color}
    class={className}
  />
{:else}
  <span class="text-red-500 text-xs">Icon "{name}" not found</span>
{/if}
